name: InventoryManager
version: 1.0
main: com.gmail.mooke.inventorymanager.InventoryManager
author: Mooke

permissions:
  shitinv.bypass.inventory:
    default: false
  shitinv.access.helmet:
    default: true
  shitinv.access.chestplate:
    default: true
  shitinv.access.leggings:
    default: true
  shitinv.access.boots:
    default: true